// City landing pages — one entry per town, rendered by app/[city]/page.js.
// Keep facts here honest: drive times from Waverly, real landmarks, no invented venues.
export const CITIES = [
  {
    slug: "elmira-ny-videographer",
    name: "Elmira",
    state: "NY",
    region: "Chemung County",
    drive: "25 minutes",
    intro: "Elmira is the biggest wedding and business market in the Twin Tiers, and it's a 25-minute drive from my door. Mark Twain country, the Chemung River, Harris Hill, barns and halls up and down Route 17 — I've filmed here and I'll be on time.",
    business: "Elmira storefronts, gyms, restaurants, and contractors are competing for the same customers on the same feeds. A Content Day gives you a month of real footage of your actual place and people — not stock.",
    nearby: ["Horseheads", "Big Flats", "Elmira Heights", "Southport", "Pine City"],
    geo: { lat: 42.0898, lng: -76.8077 },
  },
  {
    slug: "corning-ny-videographer",
    name: "Corning",
    state: "NY",
    region: "Steuben County",
    drive: "45 minutes",
    intro: "Corning weddings tend to be beautiful ones — the Gaffer District, the hills above the Chemung, the Finger Lakes wineries a short drive north. I'm 45 minutes away and film in Corning and Painted Post regularly.",
    business: "Corning's shops, restaurants, and wineries live on visitors' phones. A brand video and a set of reels shot on-site is the difference between being scrolled past and being saved.",
    nearby: ["Painted Post", "Bath", "Hammondsport", "Watkins Glen"],
    geo: { lat: 42.1428, lng: -77.0547 },
  },
  {
    slug: "ithaca-ny-videographer",
    name: "Ithaca",
    state: "NY",
    region: "Tompkins County",
    drive: "an hour",
    intro: "Ithaca weddings mean gorges, lake views, and vineyards on both sides of Cayuga. It's about an hour from Waverly, and I treat Ithaca dates the same as a hometown one, and travel is included.",
    business: "Ithaca businesses have a story-driven audience — students, faculty, tourists, locals who read the about page. A Content Day gives you the footage to tell that story on Instagram, TikTok, and your site.",
    nearby: ["Trumansburg", "Lansing", "Dryden", "Newfield", "Watkins Glen"],
    geo: { lat: 42.4440, lng: -76.5019 },
  },
  {
    slug: "waverly-ny-videographer",
    name: "Waverly",
    state: "NY",
    region: "Tioga County",
    drive: "home base",
    home: true,
    intro: "Waverly is home. I live and work right here at the New York–Pennsylvania line, so a Waverly wedding or shoot means no travel, no rush, and someone who already knows the area.",
    business: "Waverly shops, restaurants, and service businesses are competing with every feed in the Valley. A Content Day gives you a month of real footage of your own place and people, shot by someone down the street.",
    nearby: ["Sayre", "Athens", "Chemung", "Lockwood", "Nichols"],
    geo: { lat: 42.0103, lng: -76.5274 },
  },
  {
    slug: "sayre-pa-videographer",
    name: "Sayre",
    state: "PA",
    region: "Bradford County",
    drive: "5 minutes",
    intro: "Sayre is five minutes from my door, right across the state line in the Valley. Weddings, family sessions, and business shoots here are hometown work for me.",
    business: "Sayre businesses serve the whole Valley, including a lot of people who just moved here. A Content Day gives you promo videos, reels, and photos that show them exactly who you are.",
    nearby: ["Athens", "South Waverly", "Ulster", "Milan", "Waverly"],
    geo: { lat: 41.979, lng: -76.5155 },
  },
  {
    slug: "athens-pa-videographer",
    name: "Athens",
    state: "PA",
    region: "Bradford County",
    drive: "10 minutes",
    intro: "Athens sits at Tioga Point, where the Susquehanna and the Chemung meet, about ten minutes from Waverly. River light, old streets, and wide-open farm country make it an easy place to film something beautiful.",
    business: "Athens shops and contractors mostly win on word of mouth. A promo video and a set of reels put that word of mouth on every phone in the Valley.",
    nearby: ["Sayre", "Ulster", "Milan", "Litchfield", "Towanda"],
    geo: { lat: 41.9573, lng: -76.518 },
  },
  {
    slug: "owego-ny-videographer",
    name: "Owego",
    state: "NY",
    region: "Tioga County",
    drive: "25 minutes",
    intro: "Owego's historic Front Street and its riverwalk along the Susquehanna are made for photos and film. It's about 25 minutes from Waverly, and travel is included.",
    business: "Owego's downtown shops and restaurants depend on visitors finding them online first. Reels and a short promo shot on-site help them stop scrolling and come in.",
    nearby: ["Apalachin", "Candor", "Nichols", "Newark Valley", "Tioga Center"],
    geo: { lat: 42.1034, lng: -76.2622 },
  },
  {
    slug: "towanda-pa-videographer",
    name: "Towanda",
    state: "PA",
    region: "Bradford County",
    drive: "30 minutes",
    intro: "Towanda is about 30 minutes down Route 220 from Waverly, along the Susquehanna, with Endless Mountains views and plenty of barns and back roads. Travel is included.",
    business: "Towanda businesses cover a lot of miles of Bradford County. A Content Day gives you the videos and photos to reach people across all of it.",
    nearby: ["Wysox", "Monroeton", "Wyalusing", "Troy", "Athens"],
    geo: { lat: 41.7676, lng: -76.443 },
  },
  {
    slug: "binghamton-ny-videographer",
    name: "Binghamton",
    state: "NY",
    region: "Broome County",
    drive: "45 minutes",
    intro: "Binghamton, the carousel capital of the world, is about 45 minutes from Waverly. From downtown halls to venues out in the hills, I film Binghamton-area weddings with the same care as a hometown one, and travel is included.",
    business: "Binghamton is a bigger, busier market, and local businesses need to stand out on the feed. A Content Day gives you a promo video, reels, and photos built for exactly that.",
    nearby: ["Vestal", "Johnson City", "Endicott", "Conklin", "Kirkwood"],
    geo: { lat: 42.0987, lng: -75.918 },
  },
];

export const findCity = (slug) => CITIES.find((c) => c.slug === slug);
